---
version: 2
jobs:
  build:
    docker:
    - image: suzukishunsuke/go-ci:0.5.0
    working_directory: /go/src/github.com/suzuki-shunsuke/gomic
    steps:
    - checkout
    - run: npm i
    - run: dep-dl
    - run: bash scripts/commitlint-circleci.sh
    - run: npm run lint
    - run: bash scripts/codecov-test.sh
    - run: test "$LOCAL" == "true" || bash <(curl -s https://codecov.io/bash)
    - run: bash scripts/release.sh
workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
